swaywm/swayidle

main.c
swayidle.1.scd

See https://github.com/swaywm/sway/pull/3382

Add ability to wait for command to finish

---

main.c

This also fixes a bug where the signals didn't have a name for the sender,
sd_bus_match_signal handles that case, where sd_bus_add_match did not
match the signals.
from `sudo busctl monitor` I see:
```
‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=944
Sender=:1.3  Path=/org/freedesktop/login1  Interface=org.freedesktop.login1.Manager  Member=PrepareForSleep
UniqueName=:1.3
MESSAGE "b" {
BOOLEAN true;
};
```
and
```
‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=950
Sender=:1.3  Path=/org/freedesktop/login1  Interface=org.freedesktop.login1.Manager  Member=PrepareForSleep
UniqueName=:1.3
MESSAGE "b" {
BOOLEAN false;
};
```
OS is ArchLinux with systemd 240.34-3

use sd_bus_match_signal instead of sd_bus_add_match

---

main.c
swayidle.1.scd

similar to the before-sleep, it allows the user to set a command to be run after the system resumes out of sleep.
It depends on logind sending the PrepareForSleep signal with an argument of false.

introduce an after-resume hook

---

main.c

… to be more inline with the command line option
I've found it a bit confusing that the variable was named `lock_cmd`, when it was setup by the `before_sleep` cli option, it suggested to me there might be other uses.

trivial: rename state.lock_cmd to state.before_sleep_cmd

---

README.md
swayidle.1.scd

Basically the same as https://github.com/swaywm/swaylock/pull/21, but it only affects documentation.
Two notes (just FYI, I don't want tho take a position here):
- Swayidle currently does not provide a version parameter (`-v`, `--version`). I don't think this is strictly necessary but it might make sense for users and bug reports since swayidle is now an independent package.
- The man page still references a lot of the man pages from Sway: https://github.com/swaywm/swayidle/blob/ec102c1478ab077abec288e70c931d2502c836b7/swayidle.1.scd#L77
These seem only relevant for the [example](https://github.com/swaywm/swayidle/blob/ec102c1478ab077abec288e70c931d2502c836b7/swayidle.1.scd#L55). I think that `sway`, `sway-input`, and `sway-bar` are not required anymore and `swaylock` is used in the …

Replace old Sway references with swayidle

---

main.c

Signed-off-by: Jérémy Rosen <jeremy.rosen@smile.fr>

Add an error message when before-sleep is used without dbus support

---

completions/zsh/_swayidle

Include the -w option and use describe before arguments.
It's best to use \_arguments last when invoked to let its return code propagate to compsys so the completion won't accidentally be invoked again. Try `swayidle -<TAB>` to see what I mean.

Update zsh completions

---

main.c
swayidle.1.scd

Adds a new event, `idlehint <seconds>`, which will call the `SetIdleHint` method on the logind session after the delay specified in `<seconds>`. This indicates to logind whether the session is active or idle, allowing logind `IdleAction` to be used.
Adding an `idlehint` event will also cause swayidle to call `SetIdleHint(false)` when first run, on idle resume, unlock, etc. 
This should resolve #4

Adds logind SetIdleHint event - resolves #4

---

meson.build

It seems this gets forgotten before doing a release.
Like last time:
* https://github.com/swaywm/swayidle/pull/30
* https://github.com/swaywm/swayidle/pull/34
So this time I will try differently and set it to the (probably)
next version number :-)

Set version to 1.7

---

main.c
swayidle.1.scd

This executes all pending resumes (in undefined order, see #54 ) when receinving `SIGTERM`.
This is achieved by adding a `boolean resume_pending` to `struct swayidle_timeout_cmd`.
Closes #49

Run resume commands on SIGTERM

---

main.c

This isn't provided by POSIX. For getopt, only unistd.h is required.

Remove getopt.h include

---

main.c
meson.build
swayidle.1.scd

The config parsing is done by reading the config line by line and converting them to command line arguments with ` wordexp.h`.
This also adds init and finish functions for state.
Closes #17

Add config parsing

---

main.c

Use the logind magic "auto" session to detect the session name. As a fallback, attempt to determine session name by PID.
This approach should succeed even when launched from a process not associated with a specific session, for example when started as a systemd user service.

Use logind "auto" session

---

main.c
swayidle.1.scd

Adds support for logind idle inhibitor locks. Specifically:
* swayidle will disable all idle timers when a logind idle inhibitor lock is found
In addition, a few of the logind functions were rearranged and tweaked to support this feature.
This should resolve issue #38 , and would replace/supercede PR #26 and #40

Add support for logind idle inhibitors

---

main.c

See https://github.com/swaywm/swayidle/issues/38#issuecomment-621724409
Running `sd_bus_message_unref()` overrides the `locks` buffer under certain
conditions.
Comparing before running `sd_bus_message_unref()` will make sure that the
inhibit lock will always be found correctly.
@electrickite

Fix race condition in get_logind_idle_inhibit()

---

main.c
swayidle.1.scd

Might address #1.The seat name can be specified by the "-S" option. Otherwise an arbitrary seat will be picked.
I think it would be cool to be able to track a specified array of seats, but looks like that will require a healthy rewrite.

Add seat selection

---

swayidle.1.scd

It appears scdoc requires backslashes to be escaped. Now, the manpage
renders with a single backslash followed by a newline, as opposed to no
backslash.

escape backslashes in manpage example

---

swayidle.1.scd

In the previous commit I forgot to escape the first backslash.

actually fix all manpage backslashes

---

main.c

getline returns a string without a newline if the config file doesn't have a final newline.
Closes: #70
Signed-off-by: apiraino <apiraino@users.noreply.github.com>

Fix last character of config file dropped

---

main.c

resume_cmd and idle_cmd members of swayidle_timeout_cmd were never freed
even though the strings are allocated by strdup().

free resume_cmd and idle_cmd at swayidle_finish

---

main.c

In order to remove element from wl_list, only wl_list_remove should be
called. Remove the broken call to wl_list_init before that.

remove broken wl_list_remove from swayidle_finish

---

main.c

PropertiesChanged signal dbus message contains an array of elements that
contain two fields:
- First is string type field containing the property name
- Second is variant type field containing the property value
Previously the logic in iterating through these properties and the
fields in them wasn't working properly:
- `sd_bus_message_skip` was called with wrong type and the return value
of that wasn't checked: it was actually -6 indicating an error
- `sd_bus_exit_container` was not called after each property element and
before attempting to enter next changed property.
These caused the attempt to enter the second changed property with
`sd_bus_message_enter_container` to fail with -6. And if multiple
properties had been changed, only first of them was actually checked.
This commit fixes …

Fix message handling for PropertiesChanged signal

---

main.c

I ran clang-tidy against swayidle and it detected several problems. This PR addresses those problems.
However, clang-tidy also warns about the use of `memset` and `sprintf` and suggests to replace them with C11 functions `memset_s` and `sprintf_s` respectively. Those warnings are not addressed in this PR.

Fix clang tidy detections

---

main.c

This fixes https://github.com/swaywm/sway/issues/6657.

Call release() to let the server remove the timer.

---

log.h
main.c

Main motivation was to add time prefixes for easier debugging when viewing 
together with swaylock logs, however I ended up just taking the implementation
from swaylock itself, including the colouring of the output.

Improve log messages

---

meson.build

Fixes the following:
NOTICE: Future-deprecated features used:
* 0.55.0: {'ExternalProgram.path'}
* 0.56.0: {'dependency.get_pkgconfig_variable'}

build: simplify and stop using deprecated features

---

swayidle.1.scd

sway-output(5) lists `dpms` as deprecated and an alias for `power`. For
clarity and consistency, the `swayidle(1)` man page should use `power`
in the example command

Replace `dpms` commands with `power` in sample command

---

swayidle.1.scd

A stop is missing in the manpage. This pull request adds it.

Add a missing stop in the manpage

---

main.c
meson.build

fixes #51
The idle-notify protocol [recently gained](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/367) a new method get_input_idle_notification() that allows to ignore idle inhibitors. I didn't want to change the behavior of SIGUSR1 to keep backwards compatibility, so I added SIGUSR2 with the new behavior.
I was also unsure whether to add a boolean argument to `register_timeout` or add a new function. I went with the former option.

Allow to ignore idle inhibitors
